### ISSUE TITLE
url is password protected

### ISSUE THREAD

**Issue by TonhaoSemAcento** [totvs/dcp-extension#6]
Install the extension in vscode, when running the docker-compose can't download because url refuses the connection. In the https://totvs.io/ redirects to https://protheus.totvs.io/ and asks for password

Below is the output from terminal:

C:\Repos\docker>docker-compose -f protheus-dev-sandbox.yml up
Pulling license (docker.totvs.io/dcp/license:)...
ERROR: Get https://docker.totvs.io/v2/: dial tcp 138.219.88.137:443: connect: connection refused

C:\Repos\docker>

**Comment by endersonmaia** [comment]
@TonhaoSemAcento acredito ter sido uma intermitência no serviço, testando agora, funcionou

**Comment by TonhaoSemAcento** [comment]
@endersonmaia Consegui aqui também!
